// Extended mock data for the beat marketplace

export interface Beat {
  id: string
  title: string
  producer: string
  producerAvatar?: string
  bpm: number
  key: string
  genre: string
  price: number
  imageUrl: string
  audioUrl: string
  tags: string[]
  likes: number
  plays: number
  matchScore?: number
  duration?: string
  description?: string
  exclusive?: boolean
  leasePrice?: number
}

export const MOCK_BEATS: Beat[] = [
  {
    id: "1",
    title: "Midnight Hustle",
    producer: "TriuneBeats",
    producerAvatar: "/rapper-avatar-1.jpg",
    bpm: 140,
    key: "C Minor",
    genre: "Trap",
    price: 29.99,
    leasePrice: 19.99,
    imageUrl: "/dark-trap-beat-cover.jpg",
    audioUrl: "/beats/midnight-hustle.mp3",
    tags: ["Dark", "Aggressive", "Hard"],
    likes: 234,
    plays: 1523,
    duration: "3:24",
    description: "Hard-hitting trap beat with dark vibes perfect for aggressive flows",
  },
  {
    id: "2",
    title: "Golden Hour",
    producer: "TriuneBeats",
    producerAvatar: "/rapper-avatar-2.jpg",
    bpm: 85,
    key: "G Major",
    genre: "Boom Bap",
    price: 24.99,
    leasePrice: 14.99,
    imageUrl: "/golden-sunset-hip-hop.jpg",
    audioUrl: "/beats/golden-hour.mp3",
    tags: ["Chill", "Smooth", "Jazzy"],
    likes: 456,
    plays: 2891,
    duration: "2:58",
    description: "Smooth boom bap with jazzy samples and laid-back vibes",
  },
  {
    id: "3",
    title: "Street Dreams",
    producer: "TriuneBeats",
    producerAvatar: "/rapper-avatar-3.jpg",
    bpm: 95,
    key: "D Minor",
    genre: "Lo-Fi",
    price: 19.99,
    leasePrice: 12.99,
    imageUrl: "/urban-street-night-lofi.jpg",
    audioUrl: "/beats/street-dreams.mp3",
    tags: ["Melancholic", "Atmospheric", "Deep"],
    likes: 189,
    plays: 987,
    duration: "3:12",
    description: "Atmospheric lo-fi beat with deep emotional undertones",
  },
  {
    id: "4",
    title: "Victory Lap",
    producer: "TriuneBeats",
    producerAvatar: "/rapper-avatar-4.jpg",
    bpm: 150,
    key: "E Minor",
    genre: "Trap",
    price: 34.99,
    leasePrice: 24.99,
    imageUrl: "/victory-championship-energy.jpg",
    audioUrl: "/beats/victory-lap.mp3",
    tags: ["Triumphant", "Energetic", "Hype"],
    likes: 678,
    plays: 4521,
    duration: "3:45",
    description: "High-energy trap anthem perfect for victory moments",
    exclusive: true,
  },
  {
    id: "5",
    title: "Late Night Thoughts",
    producer: "TriuneBeats",
    producerAvatar: "/rapper-avatar-5.jpg",
    bpm: 70,
    key: "A Minor",
    genre: "R&B",
    price: 27.99,
    leasePrice: 17.99,
    imageUrl: "/late-night-city-lights-rnb.jpg",
    audioUrl: "/beats/late-night.mp3",
    tags: ["Emotional", "Slow", "Soulful"],
    likes: 312,
    plays: 1876,
    duration: "4:02",
    description: "Soulful R&B ballad with emotional depth",
  },
  {
    id: "6",
    title: "Flex Mode",
    producer: "TriuneBeats",
    producerAvatar: "/rapper-avatar-1.jpg",
    bpm: 130,
    key: "F# Minor",
    genre: "Trap",
    price: 29.99,
    leasePrice: 19.99,
    imageUrl: "/luxury-flex-trap-beat.jpg",
    audioUrl: "/beats/flex-mode.mp3",
    tags: ["Bouncy", "Club", "Catchy"],
    likes: 523,
    plays: 3214,
    duration: "3:18",
    description: "Bouncy trap beat with club-ready energy",
  },
  {
    id: "7",
    title: "Neon Nights",
    producer: "SynthWave",
    producerAvatar: "/rapper-avatar-2.jpg",
    bpm: 120,
    key: "B Minor",
    genre: "Synthwave",
    price: 32.99,
    leasePrice: 22.99,
    imageUrl: "/dark-trap-beat-cover.jpg",
    audioUrl: "/beats/neon-nights.mp3",
    tags: ["Retro", "Cyberpunk", "Vibey"],
    likes: 789,
    plays: 5234,
    duration: "3:30",
    description: "Retro-futuristic synthwave with cyberpunk aesthetics",
  },
  {
    id: "8",
    title: "Cloud Nine",
    producer: "Elevate",
    producerAvatar: "/rapper-avatar-3.jpg",
    bpm: 88,
    key: "C Major",
    genre: "Cloud Rap",
    price: 26.99,
    leasePrice: 16.99,
    imageUrl: "/golden-sunset-hip-hop.jpg",
    audioUrl: "/beats/cloud-nine.mp3",
    tags: ["Ethereal", "Dreamy", "Floating"],
    likes: 445,
    plays: 2345,
    duration: "2:45",
    description: "Dreamy cloud rap beat with ethereal vibes",
  },
  {
    id: "9",
    title: "Underground King",
    producer: "StreetSound",
    producerAvatar: "/rapper-avatar-4.jpg",
    bpm: 92,
    key: "D Minor",
    genre: "Boom Bap",
    price: 22.99,
    leasePrice: 14.99,
    imageUrl: "/urban-street-night-lofi.jpg",
    audioUrl: "/beats/underground-king.mp3",
    tags: ["Raw", "Gritty", "Classic"],
    likes: 567,
    plays: 3456,
    duration: "3:15",
    description: "Classic boom bap with raw underground energy",
  },
  {
    id: "10",
    title: "Electric Dreams",
    producer: "FutureBeats",
    producerAvatar: "/rapper-avatar-5.jpg",
    bpm: 135,
    key: "G# Minor",
    genre: "Trap",
    price: 31.99,
    leasePrice: 21.99,
    imageUrl: "/victory-championship-energy.jpg",
    audioUrl: "/beats/electric-dreams.mp3",
    tags: ["Futuristic", "Electric", "Bass"],
    likes: 623,
    plays: 4123,
    duration: "3:52",
    description: "Futuristic trap with heavy bass and electric energy",
  },
  {
    id: "11",
    title: "Soul Search",
    producer: "DeepSoul",
    producerAvatar: "/rapper-avatar-1.jpg",
    bpm: 75,
    key: "E Minor",
    genre: "R&B",
    price: 28.99,
    leasePrice: 18.99,
    imageUrl: "/late-night-city-lights-rnb.jpg",
    audioUrl: "/beats/soul-search.mp3",
    tags: ["Soulful", "Introspective", "Deep"],
    likes: 389,
    plays: 1987,
    duration: "4:15",
    description: "Deep soulful R&B with introspective vibes",
  },
  {
    id: "12",
    title: "Rise Up",
    producer: "Motivational",
    producerAvatar: "/rapper-avatar-2.jpg",
    bpm: 145,
    key: "A Minor",
    genre: "Trap",
    price: 33.99,
    leasePrice: 23.99,
    imageUrl: "/luxury-flex-trap-beat.jpg",
    audioUrl: "/beats/rise-up.mp3",
    tags: ["Motivational", "Powerful", "Uplifting"],
    likes: 892,
    plays: 5678,
    duration: "3:28",
    description: "Powerful trap anthem for motivation and success",
    exclusive: true,
  },
  {
    id: "13",
    title: "Midnight Drive",
    producer: "NightRider",
    producerAvatar: "/rapper-avatar-3.jpg",
    bpm: 105,
    key: "F Minor",
    genre: "Lo-Fi",
    price: 21.99,
    leasePrice: 13.99,
    imageUrl: "/dark-trap-beat-cover.jpg",
    audioUrl: "/beats/midnight-drive.mp3",
    tags: ["Chill", "Relaxing", "Smooth"],
    likes: 234,
    plays: 1234,
    duration: "2:55",
    description: "Smooth lo-fi perfect for late night drives",
  },
  {
    id: "14",
    title: "Hustle Hard",
    producer: "GrindMode",
    producerAvatar: "/rapper-avatar-4.jpg",
    bpm: 155,
    key: "C# Minor",
    genre: "Trap",
    price: 35.99,
    leasePrice: 25.99,
    imageUrl: "/golden-sunset-hip-hop.jpg",
    audioUrl: "/beats/hustle-hard.mp3",
    tags: ["Aggressive", "Hard", "Grind"],
    likes: 756,
    plays: 4890,
    duration: "3:40",
    description: "Hard-hitting trap for the grind",
  },
  {
    id: "15",
    title: "Sunset Vibes",
    producer: "ChillBeats",
    producerAvatar: "/rapper-avatar-5.jpg",
    bpm: 80,
    key: "A Major",
    genre: "Chill Hop",
    price: 23.99,
    leasePrice: 15.99,
    imageUrl: "/urban-street-night-lofi.jpg",
    audioUrl: "/beats/sunset-vibes.mp3",
    tags: ["Chill", "Relaxed", "Vibey"],
    likes: 412,
    plays: 2567,
    duration: "3:05",
    description: "Chill hop beat with relaxed sunset vibes",
  },
  {
    id: "16",
    title: "Dark Matter",
    producer: "Cosmic",
    producerAvatar: "/rapper-avatar-1.jpg",
    bpm: 125,
    key: "B Minor",
    genre: "Trap",
    price: 30.99,
    leasePrice: 20.99,
    imageUrl: "/victory-championship-energy.jpg",
    audioUrl: "/beats/dark-matter.mp3",
    tags: ["Dark", "Mysterious", "Deep"],
    likes: 534,
    plays: 3456,
    duration: "3:22",
    description: "Dark trap with mysterious cosmic energy",
  },
  {
    id: "17",
    title: "Smooth Operator",
    producer: "JazzMaster",
    producerAvatar: "/rapper-avatar-2.jpg",
    bpm: 90,
    key: "D Major",
    genre: "Jazz Rap",
    price: 27.99,
    leasePrice: 17.99,
    imageUrl: "/late-night-city-lights-rnb.jpg",
    audioUrl: "/beats/smooth-operator.mp3",
    tags: ["Jazzy", "Smooth", "Classy"],
    likes: 678,
    plays: 4321,
    duration: "3:48",
    description: "Smooth jazz rap with classy vibes",
  },
  {
    id: "18",
    title: "Fire Starter",
    producer: "Ignite",
    producerAvatar: "/rapper-avatar-3.jpg",
    bpm: 160,
    key: "E Minor",
    genre: "Trap",
    price: 36.99,
    leasePrice: 26.99,
    imageUrl: "/luxury-flex-trap-beat.jpg",
    audioUrl: "/beats/fire-starter.mp3",
    tags: ["Intense", "Fire", "Energy"],
    likes: 945,
    plays: 6789,
    duration: "3:15",
    description: "High-intensity trap that ignites the fire",
    exclusive: true,
  },
]

export const GENRES = ["All", "Trap", "Boom Bap", "Lo-Fi", "R&B", "Synthwave", "Cloud Rap", "Chill Hop", "Jazz Rap"]

export const PRODUCERS = [
  { id: "1", name: "TriuneBeats", avatar: "/rapper-avatar-1.jpg", beats: 24, followers: "12.5K" },
  { id: "2", name: "SynthWave", avatar: "/rapper-avatar-2.jpg", beats: 18, followers: "8.9K" },
  { id: "3", name: "Elevate", avatar: "/rapper-avatar-3.jpg", beats: 15, followers: "6.2K" },
  { id: "4", name: "StreetSound", avatar: "/rapper-avatar-4.jpg", beats: 22, followers: "10.1K" },
  { id: "5", name: "FutureBeats", avatar: "/rapper-avatar-5.jpg", beats: 19, followers: "9.3K" },
]

export const TESTIMONIALS = [
  {
    id: "1",
    name: "MC Flow",
    username: "@mcflow",
    avatar: "/rapper-avatar-1.jpg",
    text: "The AI filter found me the perfect beat in seconds. This platform is a game changer for artists!",
    rating: 5,
  },
  {
    id: "2",
    name: "Lyric Queen",
    username: "@lyricqueen",
    avatar: "/rapper-avatar-2.jpg",
    text: "Best beat marketplace I've used. The quality is insane and the smart filter actually works!",
    rating: 5,
  },
  {
    id: "3",
    name: "Beat Seeker",
    username: "@beatseeker",
    avatar: "/rapper-avatar-3.jpg",
    text: "Found my hit song here. The recording booth feature is incredible for testing beats.",
    rating: 5,
  },
  {
    id: "4",
    name: "Rhyme Master",
    username: "@rhymemaster",
    avatar: "/rapper-avatar-4.jpg",
    text: "The community here is amazing. So many talented producers and artists collaborating.",
    rating: 5,
  },
]



